### ISSUE TITLE
命令行执行报错

### ISSUE THREAD

**Issue by sgjeff** [tobyqin/xmindparser#7]
Traceback (most recent call last):
  File "/usr/local/bin/xmindparser", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/xmindparser/main.py", line 22, in main
    out = xmind_to_file(xmind, out_types)
  File "/usr/local/lib/python2.7/site-packages/xmindparser/__init__.py", line 75, in xmind_to_file
    return xmind_to_json(file_path)
  File "/usr/local/lib/python2.7/site-packages/xmindparser/__init__.py", line 87, in xmind_to_json
    with open(target, 'w', encoding='utf8') as f:
TypeError: 'encoding' is an invalid keyword argument for this function

**Comment by sgjeff** [comment]
使用环境 mac

**Comment by tobyqin** [comment]
python 2.7 不支持处理中文xmind，如果xmind里有unicode请使用python 3.5以上
